#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sinegen.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

#build c++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

#run executable simulation file
obj_dir/Vsinegen
